# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(287, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineResultado = QtWidgets.QLineEdit(self.centralwidget)
        self.lineResultado.setObjectName("lineResultado")
        self.gridLayout_2.addWidget(self.lineResultado, 5, 0, 1, 3)
        self.pushDias = QtWidgets.QPushButton(self.centralwidget)
        self.pushDias.setObjectName("pushDias")
        self.gridLayout_2.addWidget(self.pushDias, 6, 0, 1, 1)
        self.pushDiasUteis = QtWidgets.QPushButton(self.centralwidget)
        self.pushDiasUteis.setObjectName("pushDiasUteis")
        self.gridLayout_2.addWidget(self.pushDiasUteis, 9, 1, 1, 1)
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setObjectName("labelResultado")
        self.gridLayout_2.addWidget(self.labelResultado, 4, 0, 1, 3)
        self.pushAnos = QtWidgets.QPushButton(self.centralwidget)
        self.pushAnos.setObjectName("pushAnos")
        self.gridLayout_2.addWidget(self.pushAnos, 6, 2, 1, 1)
        self.labelOperacao = QtWidgets.QLabel(self.centralwidget)
        self.labelOperacao.setObjectName("labelOperacao")
        self.gridLayout_2.addWidget(self.labelOperacao, 2, 0, 1, 3)
        self.pushDiaSemana = QtWidgets.QPushButton(self.centralwidget)
        self.pushDiaSemana.setObjectName("pushDiaSemana")
        self.gridLayout_2.addWidget(self.pushDiaSemana, 8, 1, 1, 1)
        self.labelCalcDatas = QtWidgets.QLabel(self.centralwidget)
        self.labelCalcDatas.setObjectName("labelCalcDatas")
        self.gridLayout_2.addWidget(self.labelCalcDatas, 0, 0, 1, 3)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 11, 2, 1, 1)
        self.pushHoje = QtWidgets.QPushButton(self.centralwidget)
        self.pushHoje.setObjectName("pushHoje")
        self.gridLayout_2.addWidget(self.pushHoje, 7, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 267, 210))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textHistorico = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textHistorico.setObjectName("textHistorico")
        self.gridLayout_3.addWidget(self.textHistorico, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 3)
        self.pushMeses = QtWidgets.QPushButton(self.centralwidget)
        self.pushMeses.setObjectName("pushMeses")
        self.gridLayout_2.addWidget(self.pushMeses, 6, 1, 1, 1)
        self.lineOperacao = QtWidgets.QLineEdit(self.centralwidget)
        self.lineOperacao.setObjectName("lineOperacao")
        self.gridLayout_2.addWidget(self.lineOperacao, 3, 0, 1, 3)
        self.pushDiferenca = QtWidgets.QPushButton(self.centralwidget)
        self.pushDiferenca.setObjectName("pushDiferenca")
        self.gridLayout_2.addWidget(self.pushDiferenca, 10, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.pushDias.setText(_translate("MainWindow", "Dias"))
        self.pushDiasUteis.setText(_translate("MainWindow", "Dias úteis entre datas"))
        self.labelResultado.setText(_translate("MainWindow", "Resultado"))
        self.pushAnos.setText(_translate("MainWindow", "Anos"))
        self.labelOperacao.setText(_translate("MainWindow", "Operação"))
        self.pushDiaSemana.setText(_translate("MainWindow", "Dia da semana"))
        self.labelCalcDatas.setText(_translate("MainWindow", "Calculadora de datas"))
        self.pushButton_8.setText(_translate("MainWindow", "Sair"))
        self.pushHoje.setText(_translate("MainWindow", "Hoje"))
        self.pushMeses.setText(_translate("MainWindow", "Meses"))
        self.pushDiferenca.setText(_translate("MainWindow", "Diferença entre datas"))
